#!/bin/bash

rm arctic*

echo "-----------------repo-add----------------"
repo-add -n -R arctic.db.tar.gz *.pkg.tar.zst

echo "===================================="
echo "Repo Updated!!"
echo "===================================="

