#!/bin/bash

rm arctic_repo*

echo "-----------------repo-add----------------"
repo-add -n -R arctic_repo.db.tar.gz *.pkg.tar.zst

echo "===================================="
echo "Repo Updated!!"
echo "===================================="

